Stage#0 - CV#1 Markdown & Git - deploy description and pr link
rolling-scopes-school/tasks pull request #1071
Opened 2023-06-29 00:20 UTC by lyutails

hey there o/
add how to make deploy description plus which link to paste in pull request to lower number of questions in discord channels
@etroynov take a look at please

2023-06-29 16:48 UTC, etroynov requested changes

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
>  ## Как сабмитить задание
```suggestion
## Отправка задания на проверку
```

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
> +## Deploy
```suggestion
## Публикация резюме на `github-pages` ( Deploy )
```

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
> +Чтобы найти деплой своего задания (и вставить ссылку на него в третий пункт описания пулл реквеста):
```suggestion
Для того чтобы найти ссылку на опубликованное ранее вами резюме (и добавить ее в третий пункт описания пулл реквеста):
```

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
> +- в своём репозитории в правом нижнем углу найдите Environments
```suggestion
- находясь в своём репозитории в правой части найдите блок `Environments` ( как правило он располагается нижнем углу );
```

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
> +- щёлкните на `github-pages` около ракеты 🚀 и в откывшемся окне нажмите на `View Deployment` - откроется свёрстанный сайт / приложение
```suggestion
- нажмите на `github-pages` ( около иконки ракеты 🚀 ) и в открывшемся окне нажмите на `View Deployment` при этом должен будет открыться сайт с сверстанным вами резюме;
```

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
> +- если в gh-pages есть файл с расширением .md - то он будет открываться на деплое, если в корне есть файл index.html - то gh-pages сработает как хостинг для него (путь в url будет вести к нему)
```suggestion
- сервис `gh-pages` позволяет вам публиковать вам контент в интернете ( т.е он становится публичным и кто угодно может его увидеть ) в качестве контента используются файлы с расширением `.md`, однако если в корне репозитория есть файл с расширением `index.html` то он будет использоваться в качестве главной страницы поскольку имеет более высокий приоритет по сравнению с `.md` файлами;
```

2023-06-29 16:48 UTC, etroynov commented on tasks/cv/git-markdown.md
> +- CV#1 проверяется сабмитом в автотест и бот должен увидеть, что третий пункт описания пулл реквеста заполнен (чтобы самбит прошёл), на следующей неделе кросс-чеком будет проверяться вёрстка CV#3, вы
```suggestion
- первое задание ( CV#1 ) проверяется автоматически при создании PR ( pull request ), для этого наш бот переходит на страницу с PR и проверяет что 3 пункт содержит корректную ссылку на сайт с вашим резюме.  Далее через неделю, на этапе кросс-чека будет проверяться вёрстка задания ( CV#3 ), выполненное с помощью html/css. *Примечание:* в третьем пункте пулл реквеста можно указать ссылку на сверстанное резюме ( с помощью HTML/CSS);
```

2023-06-30 04:41 UTC, WiiJoy commented on tasks/cv/git-markdown.md
> +- первое задание (CV#1) проверяется автоматически при создании PR (pull request), для этого наш бот переходит на страницу с PR и проверяет что 3 пункт содержит корректную ссылку на сайт с вашим резюм
Не уверен, что бот работает с явным содержимым pr.
Наличие репозитория с указанным наименованием, возможно восстановление ссылки или какие-то подобные действия (в тч проверка наличия пр), проверка префиксов для наименований коммитов и количества коммитов

2023-06-30 04:41 UTC, WiiJoy commented on tasks/cv/git-markdown.md
> +## Публикация резюме на `github-pages` (Deploy)
Не резюме, а CV (прыжки по текстам таска между "CV" и "Резюме" - не круто). И оно уже "опубликовано", тк изначально выполняется в ветке gh-pages (которая по-умолчанию автоматически выполняет деплой содержимого с доступом по линку стандартного вида)

2023-06-30 04:41 UTC, WiiJoy commented on tasks/cv/git-markdown.md
> +- После окончания работы над заданием зайдите в rs app https://app.rs.school/, выберите **Auto-Test**, в выпадающем списке выберите название задания, нажмите кнопку **Submit**. Справа отобразится рез
Результат (score, accuracy, details) может отобразиться не сразу (время обработки). Если после сабмита стоят нули и пропуски - можно обновить страницу с результатами (кнопкой refresh)

2023-06-30 04:41 UTC, WiiJoy commented on tasks/cv/git-markdown.md
> +- нажмите на `github-pages` (около иконки ракеты 🚀) и в открывшемся окне нажмите на `View Deployment` при этом должен будет открыться сайт со сверстанным вами резюме;
Полезная инфа. Но в рамках школы - актуально только на текущем таске. Файлы для деплоя почти всех практических тасков школы размещаются в отдельной папке по названию таска
Возможно, стоит дать пояснение, что этот способ открывает деплой главной директории содержимого gh-pages, а так же дать более универсальный способ получить ссылку на деплой интересующего таска (для **личных** репозиториев - `https://GITHUB-USERNAME.github.io/название-репозитория/путь-к-открываемому-файлу-деплоя`)

Сама же стандартная ссылка, которая предполагается на выходе, указана в порядке работы, а подобная инфа, на мой взгляд, все же лучше бы смотрелась в хелпере работы с гитом, который расположен в разделе материалов к этому таску, и/или в советах по выполнению работы

2023-06-30 04:41 UTC, WiiJoy commented on tasks/cv/git-markdown.md
> +- первое задание (CV#1) проверяется автоматически при создании PR (pull request), для этого наш бот переходит на страницу с PR и проверяет что 3 пункт содержит корректную ссылку на сайт с вашим резюм
Этапы работы и типы проверок описаны в основном файле CV.md и здесь, мне кажется, это лишнее

2023-06-30 05:58 UTC, lyutails commented on tasks/cv/git-markdown.md
> +## Публикация резюме на `github-pages` (Deploy)
ну меня конечно раз спросили - а что такое cv :) говорю - curriculum vitae - резюме, но вроде это в большинстве случаев и так понятно и люди знают что это аналоги :Р

2023-06-30 06:00 UTC, lyutails commented on tasks/cv/git-markdown.md
> +- первое задание (CV#1) проверяется автоматически при создании PR (pull request), для этого наш бот переходит на страницу с PR и проверяет что 3 пункт содержит корректную ссылку на сайт с вашим резюм
ага тут поправила спасибо :) вероятно да бот проверяет префиксы, количество коммитов и что пр есть и заполнен, просто вопросы в дисе сыпятся что куда зачем вставлять вот может им тут ещё про это и расписать

2023-06-30 06:02 UTC, lyutails commented on tasks/cv/git-markdown.md
> +- После окончания работы над заданием зайдите в rs app https://app.rs.school/, выберите **Auto-Test**, в выпадающем списке выберите название задания, нажмите кнопку **Submit**. Справа отобразится рез
эммм тут поменян только заголовок :) содержание пункта прежнее, но про кнопку рефреш можно добавить и чтоб не жали бесконечно ddos(я) сайт

2023-06-30 06:39 UTC, WiiJoy commented on tasks/cv/git-markdown.md
> +- После окончания работы над заданием зайдите в rs app https://app.rs.school/, выберите **Auto-Test**, в выпадающем списке выберите название задания, нажмите кнопку **Submit**. Справа отобразится рез
Про заголовок понял, но раз уж вопрос про добавление каких-то уточняющих моментов - то вопрос про отображение результата после сабмита в принципе имеет право на уточнение)

2023-06-30 07:55 UTC, Luffi2539 commented on tasks/cv/git-markdown.md
> +- NB! Если при сабмите появляется ошибка "Error: Temporary Github Error. Cannot get commits. Please try in 10 mins." это значит, что система перегружена и не может получить информацию о ваших коммита
тут немного неверно у нас есть лимит запросов, очереди нет, поэтому избыточные клики просто ничего не делают

2023-06-30 08:01 UTC, Luffi2539 commented on tasks/cv/git-markdown.md
> +- нажмите на `github-pages` (около иконки ракеты 🚀) и в открывшемся окне нажмите на `View Deployment` при этом должен будет открыться сайт со сверстанным вами резюме;
У нас даже есть отдельный материал по gh-pages возможно тут стоит просто ссылку на него оставить

2023-06-30 08:02 UTC, Luffi2539 commented on tasks/cv/git-markdown.md
> +## Публикация резюме на `github-pages` (Deploy)
слово сабмит в дальнейшем будет везде поэтому лчше пусть пару раз спросят :)

2023-06-30 08:21 UTC, lyutails commented on tasks/cv/git-markdown.md
> +- После окончания работы над заданием зайдите в rs app https://app.rs.school/, выберите **Auto-Test**, в выпадающем списке выберите название задания, нажмите кнопку **Submit**. Справа отобразится рез
ага добавила :) ахаха уточнение имеет право уточнений

2023-06-30 08:25 UTC, lyutails commented on tasks/cv/git-markdown.md
> +- NB! Если при сабмите появляется ошибка "Error: Temporary Github Error. Cannot get commits. Please try in 10 mins." это значит, что система перегружена и не может получить информацию о ваших коммита
спасибо, не знала, поправила <3

2023-07-01 11:31 UTC, etroynov commented on tasks/cv/git-markdown.md
> +## Публикация резюме на `github-pages` (Deploy)
> слово сабмит в дальнейшем будет везде поэтому лчше пусть пару раз спросят :)

Использование слэнговых терминов не рекомендуется в учебных материалах, но если все же они есть тогда стоит сделать словарик т.к для тех кто в теме это может и круто но для людей возраста 35+ это создает для них лишнии сложности

2023-07-01 11:35 UTC, etroynov commented on tasks/cv/git-markdown.md
> +- первое задание (CV#1) проверяется автоматически при создании PR (pull request), для этого наш бот переходит на страницу с PR и проверяет что 3 пункт содержит корректную ссылку на сайт с вашим резюм
> Этапы работы и типы проверок описаны в основном файле CV.md и здесь, мне кажется, это лишнее

только как показывает дискорд, люди либо не понимают описания задания либо пропускают и потом идут задавать одни и те же вопросы, поэтому мне кажется что дублирование не будет лишним.

2023-07-01 11:36 UTC, etroynov commented on tasks/cv/git-markdown.md
> +- NB! Если при сабмите появляется ошибка "Error: Temporary Github Error. Cannot get commits. Please try in 10 mins." это значит, что система перегружена и не может получить информацию о ваших коммита
@Luffi2539 @lyutails что такое NB?

2023-07-07 10:42 UTC, merged