spelling fixes
rolling-scopes-school/tasks pull request #1685
Opened 2024-08-12 16:29 UTC by kustikov112

#### Spelling fixes

Some spelling and wording fixes

#### This is just a spelling corrections before kicking off the course

- [ ] 🌟 New task
- [ ] 🌐 New module
- [ ] ⚙️ Update to an existing task
- [ ] 🔧 Update to an existing module
- [ ] 🔗 Update or addition of external resources or links
- [ ] 🐛 Fix in a task or related content
- [ ] 🛠 Fix in a module or related content
- [x] ✏️ Fixed a typo or grammatical error
- [ ] 🔗 Fixed a broken link
- [ ] ❓ Other (specify: **\*\*\*\***\_\_\_\_**\*\*\*\***)

#### Description

- **Brief Overview:**
 Grammar fixes for the module

#### Checklist

- [x] ✅ I have performed a self-review of my own code.
- [ ] 📝 I have commented my code, particularly in hard-to-understand areas.
- [ ] 🔧 I have made corresponding changes to the documentation (if applicable).
- [x] 🚫 My changes generate no new warnings or errors.

2024-08-13 18:02 UTC, ThorsAngerVaNeT requested changes

2024-08-13 18:02 UTC, ThorsAngerVaNeT commented on devops/modules/ci-configuration/README.md
>  Artifacts from these steps (Dockerfile and Helm chart) should be stored in a git repository, which will be available to Jenkins. You may use your applications' main repository as well.
```suggestion
Artifacts from these steps (Dockerfile and Helm chart) should be stored in a git repository, which will be available to Jenkins. You may use your application's main repository as well.
```

2024-08-14 05:48 UTC, ThorsAngerVaNeT approved these changes

2024-08-16 11:56 UTC, sergiozeppo approved these changes

2024-08-16 12:59 UTC, merged