Self education
rolling-scopes-school/tasks pull request #288
Opened 2020-11-19 16:20 UTC by irinainina

Добавлены материалы для самостоятельной подготовки студентов к RS School

2020-11-20 18:47 UTC, femiarkh requested changes

2020-11-20 18:47 UTC, femiarkh commented on tasks/self-education/materials/english.md
> +
```suggestion
Обязательно занимайтесь ежедневно. Даже если у вас мало времени, 20 минут в день эффективнее часового занятия пару раз в неделю. Используйте время, которое обычно проводите без пользы – например, время поездки в общественном транспорте.

Книги/статьи по грамматике читать нужно, но не стоит их путать с собственно английским. Грамматика нужна, чтобы погружение в язык в принципе стало возможным, не без самого погружения ваш языковой навык не будет расти. От продолжительности и разнообразия погружения напрямую зависит ваша скорость овладения языком.

Полезно перевести некоторые аспекты своей жизни полностью на изучаемый язык. Если вы любите смотреть фильмы, возьмите за правило смотреть их только на английском и неотступно следуйте ему. Да, поначалу вы будете многое упускать, поэтому начать можно с фильмов, которые вы и так хорошо знаете и хотели бы пересмотреть. Не раздражайтесь, если чего-то не понимаете, – это нормальное состояние, которое со временем уйдёт, нужно просто продолжать заниматься.

Любите художественную литературу? Отныне читайте изначально англоязычные книги только на языке оригинала. Ничего, если за день вы сможете прочитать только один абзац. Положение очень быстро изменится, если вы будете последовательны и терпеливы.

Если есть какая-то полезная статья на английском, которую вы хотите прочитать, то, даже если есть её перевод, читайте в оригинале. Если вы что-то не поймёте, то всегда сможете свериться с переводом.

Любите компьютерные игры? Поздравляю, теперь вам не нужно терпеть некачественную локализацию, ведь отныне вы будете играть исключительно в английские версии игр.

Переключите интерфейс всех своих устройств на английский язык.

Изучение языка состоит из четырёх аспектов: Reading (чтение), Listening (восприятие на слух), Writing (письмо), Speaking (речь). Что нужно учесть при изучении, так это то, что эти аспекты не взаимозаменяемые в том смысле, что, развивая один из них, вы **не** будете автоматически развивать другие. Поэтому определите свои личные приоритеты, поставьте конкретную цель ("Я хочу общаться с носителями", "Я хочу уметь читать документацию", "Я хочу свободно воспринимать английскую речь") и, отталкиваясь от цели, стройте свой план обучения.

Независимо от ваших приоритетов, главным препятствием на пути к овладению языком является лексика. Возьмите за правило выучивать 5-10 слов ежедневно (цифру определите сами в зависимости от свободного времени). Используйте SRS типа Anki. Наиболее эффективно, если вы сами составляете свои карточки, а не пользуетесь готовыми. Никогда не учите слова вне контекста, так они не запомнятся. Внесите в карточку слово, транскрипцию, перевод (на более поздних этапах – словарное определение на английском), пример(ы) предложений, аудио с произношением. Можно добавить любые подсказки (мнемонику), помогающие вам вспоминать данное слово или выражение. Добавляйте в карточку только то, что сами понимаете.

Вы можете прекрасно понимать письменную речь, но при этом быть не в силах связать двух слов на собеседовании – если это важно для вас, немедленно исправляйтесь (а именно: начинайте общаться на английском, если под рукой нет собеседников – найдите их, можно записывать себя на камеру и затем анализировать получившиеся видео).

Лучшие средства для прокачки Listening Skills: подкасты, видео на YouTube, фильмы, песни, аудиокниги. Помните, что если вы смотрите видео с субтитрами, то это в большей степени прокачка Reading, нежели Listening: мозг идёт по пути наименьшего сопротивления и будет читать, а не слушать. Поэтому, если вам важно развить именно навык восприятия на слух, отключайте субтитры.

Не стесняйтесь допускать ошибки: гораздо лучше допустить и исправить, чем промолчать и оставаться в неведении относительно своего неверного понимания.

Языковые курсы могут быть полезны главным образом тем, что помогут найти единомышленников, составить план, организоваться. Но в конечном итоге то, выучите вы язык или нет, зависит исключительно от вашего желания и упорства.

Не ждите молниеносного результата вне зависимости от того, сколько усилий прилагаете. Языку нужно время, чтобы отложиться в голове, стать воспринимаемым естественно и автоматически. Поэтому ни в коем случае не расстраивайтесь, если на первых порах ничего не понимаете или понимаете мало. Просто продолжайте.

Момент "всё, я выучил английский, больше мне не нужно заниматься" никогда не наступит, просто потому что не может наступить в принципе. Как только вы перестаёте взаимодействовать с языком, он начинает выветриваться из вашей головы. К счастью, для вас это не проблема, ведь вы уже смотрите фильмы, читаете статьи и пишете программы исключительно на английском, не так ли? 
```

2020-11-20 18:47 UTC, femiarkh commented on tasks/self-education/materials/english.md
> +- [Карточки Anki. 4000 Essential English Words](https://ankiweb.net/shared/info/1104981491)
```suggestion
- [Карточки Anki. 4000 Essential English Words](https://ankiweb.net/shared/info/1104981491)

## Каналы YouTube 
- [Learn English with Bob the Canadian] (https://www.youtube.com/channel/UCZJJTxA36ZPNTJ1WFIByaeA)
- [English with Lucy] (https://www.youtube.com/c/EnglishwithLucy)
```

2020-11-23 09:14 UTC, dzmitry-varabei commented
Привет! спасибо за материалы! Пару вопросов по твоему плану:
1) студенты будут общаться в общей discord группе в категории 2021Q1? 
2) старт stage#1 - 28 февраля. Какие дедлайны по этим таскам? 
3) оценки пойдут в зачет stage#1?

2020-11-23 09:32 UTC, dzmitry-varabei commented
4. Думаю, что описание подготовительного этапа необходимо перенести в https://docs.rs.school/#/ в секцию "подготовительный этап", а в этом репозитории оставить сами задания
![image](https://user-images.githubusercontent.com/2429680/99946619-f1242200-2d76-11eb-8d62-f077d20898a1.png)

2020-11-23 10:29 UTC, SvetlanaReutskaya commented on tasks/self-education/materials/english.md
> +
Если ваш уровень достигает хотя-бы elementery (A2) рекомендуется полностью отказаться от русскоязычных учебников в пользу аутентичных. Они намного лучше развивают все 4 аспекта языка. Начиная с уровня В1 стоит отказываться от duolinguo и подобных. Чем выше ваш уровень - тем бесполезнее все эти сайты. Они рассчитаны на новичков.

Для тех кому побыстрее и полегче, лучше всего брать за основу одну из линеек:
 Gateway 
 Total English
 Navigate
 English File
Тех кто желает побольше лексики и знаний:
 Solutions
 Outcomes
 Upstream
 Speak Out

Все они легко находятся на известном торрент трекере. Берете SB, WB и проверяете себя по ответам в TB.
Грамматические учебники - это НЕ полноценные учебники! Знаменитый Мерфи языку не научит, это просто книга для закрепления грамматики!

Паралельно важно смотреть фильмы/клипы/мультфильмы на англ. Если уровень пока не позволяет смотреть самостоятельно - на ютубе много рубрик "учим англ по фильмам/сериалам". Важно не просто смотреть фоном, а тащить оттуда всю незнакомую лексику и прорабатывать ее позднее.

Курсы, имхо, почти бесполезны, если нет регулярных занятий дома самостоятельно. Вы как наберете уровень, так же быстро его и забудете. 
Тут два выхода: либо нанимать репетитора 1 на 1, который будет регулярно давать волшебного пинка, либо самому приучить себя заниматься через день хотя бы.

Конечно, очень важно повышать общий уровень английского. Но скачать книжечку вроде OXFORD ENGLISH FOR INFORMATION TECHNOLOGY, чтобы тягать оттуда лексику очень рекомендуется.

2020-11-23 18:44 UTC, irinainina commented
> 1. студенты будут общаться в общей discord группе в категории 2021Q1?
> 2. старт stage#1 - 28 февраля. Какие дедлайны по этим таскам?
> 3. оценки пойдут в зачет stage#1?

1. Думаю, да. Какая-то площадка для общения студентам нужна
2. Всего девять заданий: три теста, три автопроверяемых таска и три задания, которые проверяются кросс-чеком
Тесты и автопроверяемые таски: дедлайн = дата старта курса
Задания, которые проверяются кросс-чеком: дедлайн = дата старта курса + неделя на кросс-чек
Нерешённым остаётся вопрос со студентами, которые присоединяются к курсу после его старта
3. Думаю, да. Эти таски - то, что в этом наборе проходили за первые две недели основного курса. Если студенты их выполнят до старта курса, начинать можно будет не с basic html/ css/ js, а с вёрстки сайта - 4 недели и таска по js - две недели. То есть на первый этап будет достаточно 6 недель

2020-11-23 20:24 UTC, sergeyshalyapin commented on tasks/self-education/materials/git.md
> +     `git clone ссылка на репозиторий`
git clone your@repo.git, где your@repo.git - ссылка на ваш репозиторий

2020-11-23 20:31 UTC, sergeyshalyapin commented on tasks/self-education/materials/html.md
> +- [блочная модель документа](http://htmlbook.ru/samlayout/blochnaya-verstka/blochnaya-model)
Попробуй посмотреть статьи на обновленном ресурсе, который называется webref.ru, там как learn.jsvascript оформлен, только верстка, делал тот же Влад Мержевич

2020-11-23 20:31 UTC, sergeyshalyapin commented on tasks/self-education/materials/tools.md
> +(базовый минимум, список может расширяться)
Я бы еще дал ссылку на интро по vscode https://code.visualstudio.com/docs/introvideos/basics

2020-11-23 20:33 UTC, sergeyshalyapin commented
Я так понимаю условия самих задач просто переезжают в self-education?

2020-11-24 06:04 UTC, irinainina commented on tasks/self-education/materials/git.md
> +     `git clone ссылка на репозиторий`
клонировать репозиторий по web URL проще

2020-11-24 06:05 UTC, irinainina commented on tasks/self-education/materials/html.md
> +- [блочная модель документа](http://htmlbook.ru/samlayout/blochnaya-verstka/blochnaya-model)
Ок, спасибо за совет. Посмотрю

2020-11-24 06:14 UTC, irinainina commented
> Я так понимаю условия самих задач просто переезжают в self-education?

В тех задачах, которые уже выдавались, Git & Markdown и Git & HTML & CSS , изменений нет. 
Ещё будут тесты по html-css, js, Как учиться в RS School, нужно подумать как будет лучше - оставить их в гугл формах или перенести в rs app. 
Ещё будут три новых таска, проверяемых кросс-чеком - вёрстка резюме, вёрстка небольшого макета, аналог webdev и небольшие таски по js, аналог ready-projects первого этапа, но немного проще.

2020-11-24 10:04 UTC, dzmitry-varabei commented
@irinainina @sergeyshalyapin 
Предлагаю чуть уточнить концепцию. А именно:

- Stage#0 - это отдельный курс/отдельный скор, “песочница” где студенты изучают основы, разбираются RSAPP и подходом RS School в  течении ~6 или менее недель.
- 28 февраля стартует stage#1. Это отдельная регистрация, новый скор, полноценное вводное занятие и тд. Мы ожидаем, что большой процент студентов уже имею хорошую подготовку (учились в rsschool ранее, учатся в профильном вузе или прошли подготовительный этап). Само содержание stage#1 без особых изменений - базовые алгоритмы, верстка лендинга, первый таск по dom, тест как учиться в RS School. Продолжительность 6-7 недель как это было раньше. 

Что думаете?

2020-11-24 10:28 UTC, irinainina commented
Такая концепция делает stage#0 бессмысленным и бесполезным. 
Задачи stage#0 
1) вынести часть материала stage#1 на самостоятельное изучение благодаря чему продолжительность stage#1 останется прежней - 6 недель вместо 10 недель как это было в текущем наборе
2) немного повысить начальный уровень знаний студентов, чтобы они не приходили совсем без подготовки
3) проверить соответствие уровня студентов базовым требованиям, которые указаны на странице курса и не пропустить тех, которые этим требованиям не соответствуют.
Но это возможно только при обязательности stage#0  для всех без исключения студентов, преемственности stage#0 и stage#1, переходе баллов из stage#0 в stage#1.
Если stage#0 проходится по желанию достаточно ограничиться списком материалов для самостоятельного ознакомления. Задания, тесты, таски и их проверка не нужны.

2020-11-24 11:32 UTC, dzmitry-varabei commented
@irinainina К сожалению, я частично с тобой не согласен :)  А именно с "обязательности stage#0 для всех без исключения студентов"
 
Для меня аудитория stage#0 это желающие "войти в айти" которые в первый раз пришли в RS School. И основная цель подготовить их к прохождению stage#1  (+ сократить его до 6-7 недель).

По поводу предложений:
1) ок
2) ок
3) против. Если оценки пойдут в зачет stage#1, то ближайший дедлайн 7-8 марта.
4) только если дедлайны будут после 7 марта
5) можем обсудить. Часть вопросов действительно имеет смысл спрашивать при регистрации, остальные после привыкания к rs school :)

2020-11-24 11:46 UTC, irinainina commented
> @irinainina К сожалению, я частично с тобой не согласен :) А именно с "обязательности stage#0 для всех без исключения студентов"

Давай считать. Три теста по тридцать вопросов - это полтора часа, если они уже всё знают, только на кнопки нажимают и отдельные вопросы гуглят. Таски Git & Markdown и Git & HTML & CSS делаются за 10 минут оба. Пусть будет полчаса. 15 задач codewars достаточно простых. По 10 минут на задачу это два с половиной часа. Один небольшой макет для вёрстки. Действительно небольшой. Часа четыре максимум. и пять мини-тасков по js на 10-15 строчек кода каждый. Пусть будет по часу. Всего получаем 14 часов. То есть две недели по часу в день для того, кто уже всё знает. Это достаточно несложная программа и не выполнить её нет никаких оснований.

2020-11-24 11:51 UTC, irinainina commented
> 3. против. Если оценки пойдут в зачет stage#1, то ближайший дедлайн 7-8 марта.

Можно сделать тесты и автопроверяемые таски до 28 как условие регистрации на stage#1, а для заданий с кросс-чеком дедлайн кросс-чека 7 марта.

2020-11-25 10:21 UTC, dzmitry-varabei commented
> Я поговорила со студентами. они тоже считают, что делать этот этап обязательным не нужно. Но если этап не обязательный, и баллы за выполненные задания никуда не идут и нигде не учитываются, то и выполнять их нет смысла. Соответственно не нужны ни тесты, ни таски, ничего. То есть предложенная идея полностью неработоспособная. PR можно закрывать.

давай поставим дедлайны по этим заданиям на первую и вторую неделю stage#1 (8 и 15 марта). Чтобы подготовленные студенты успели все выполнить за 2 недели, а остальные могли спокойно разбираться 4-6 недель

2020-11-25 20:38 UTC, irinainina commented
> > Я поговорила со студентами. они тоже считают, что делать этот этап обязательным не нужно. Но если этап не обязательный, и баллы за выполненные задания никуда не идут и нигде не учитываются, то и выполнять их нет смысла. Соответственно не нужны ни тесты, ни таски, ничего. То есть предложенная идея полностью неработоспособная. PR можно закрывать.
> 
> давай поставим дедлайны по этим заданиям на первую и вторую неделю stage#1 (8 и 15 марта). Чтобы подготовленные студенты успели все выполнить за 2 недели (нагрузка до 20 часов в неделю), а остальные могли спокойно разбираться 4-6 недель

Очевидно, что предложенный вариант не устраивает, а перестраивать его под чужое виденье, которое я к тому же не понимаю, я не буду. Вероятно, этот PR лучше закрыть, как не совпадающий с задачами курса.

2020-11-27 16:12 UTC, irinainina commented
> давай поставим дедлайны по этим заданиям на первую и вторую неделю stage#1 (8 и 15 марта). Чтобы подготовленные студенты успели все выполнить за 2 недели (нагрузка до 20 часов в неделю), а остальные могли спокойно разбираться 4-6 недель

это никак не решит проблему разного уровня уровня подготовки студентов, которые приходят на первый этап
и никак не сократит первый этап, он по-прежнему будет 10 недель: 2 недели по этим заданиям + 4 недели вёрстка + 2 недели таск js-dom + минимум две недели или больше переносы дедлайнов по просьбе студентов

можно на 14 февраля (за две недели до начала stage#1) назначить старт подготовительного этапа (а задания по нему доступны задолго до этой даты), когда можно сабмитить таски с автопроверкой и тесты (тесты лучше разместить в rs app, чтобы сразу отображались результаты) и на первый этап зачислить только тех, кто эти таски и тесты выполнил, получив за них не меньше определённого количества баллов (80-90% примерно - таски простые плюс была возможность потренироваться). Ну или зачислить на первый этап полторы-две-три тысячи студентов с лучшими результатами по результатам тасков и тестов.
28 февраля открыть сабмит по таскам, которые проверяются кросс-чеком и до конца недели их проверить.

2020-12-17 12:36 UTC, closed without merging

2020-12-17 12:38 UTC, irinainina commented
Материал добавлен в другой репозиторий https://github.com/rolling-scopes-school/stage0