Javascript Classes & Inheritance
rolling-scopes-school/tasks pull request #609
Opened 2022-05-04 18:03 UTC by Skvesh

1. Task:
   [Link to the current is here](https://github.com/rolling-scopes-school/tasks/compare/master...Skvesh:master)
2. App screenshot:
   ![image](https://user-images.githubusercontent.com/61669864/166756256-d5d9ff62-c84e-4aca-acfb-56b9ce79a8bf.png)
4. Done 4.05.22 (deadline 9.05.22)
5. Details
    - [x] Base class ES5 is implemented
    - [x] Base class ES6is implemented
    - [x] Base subclass ES5 is implemented
    - [x] Base csublass ES6is implemented

2022-05-05 06:25 UTC, gpukys requested changes

2022-05-05 06:25 UTC, gpukys commented on script.js
> +	if (typeof(value) == 'number') {
try to get into the habit of using `===`. There are very rare cases where you actually need to use the `==`

2022-05-05 06:25 UTC, gpukys commented on script.js
> +		this.str = value
Do we really need separate variables for storing the string or number? Why not just change this to `value` or something

2022-05-05 06:25 UTC, gpukys commented on script.js
> +	this.str = this.str.split('').filter(char => char !== str).join('');
what if `str` was a word, not a single character?

2022-05-06 06:06 UTC, gpukys approved these changes
Looks good to me

2022-05-07 11:29 UTC, AlreadyBored commented on script.js
> +class newCalculator {
Classes names should start from capital letter

2022-05-07 13:19 UTC, AlreadyBored commented
What is this at all? Are you sure that it should be here? :)

2022-05-07 15:26 UTC, closed without merging