Feat: add react final task en
rolling-scopes-school/tasks pull request #781
Opened 2022-08-31 07:11 UTC by valerydluski

2022-08-31 07:12 UTC, valerydluski commented
@pavelrazuvalau thanks for the translation

2022-09-02 07:42 UTC, lyolya95 approved these changes

2022-09-02 17:32 UTC, MadaShindeInai requested changes

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +Yandex Tracker, Asana, GanttPro, Github projects.*
```suggestion
There are many competitors on the market for our future application. Check out suggested analogs before start building your app: *Trello, Jira, Redmine, Bitrix24, Yandex Tracker, Asana, GanttPro, Github projects.*
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +Use https://github.com/vitaly-sazonov/kanban-rest or https://github.com/rolling-scopes-school/final-task-backend/pull/1 as a backend.
```suggestion
Use https://github.com/vitaly-sazonov/kanban-rest as a backend.
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +Regardless of the application type, it should contain:
```suggestion
Your app must contain:
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- additional functionality (for example, the ability to view all the tasks of the selected user)
```suggestion
Your app could contain:
- additional functionality (for example, the ability to view all the tasks of the selected user)
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- use your private school repository for this task
```suggestion
- teamlead should create private repo in github and invite other members 
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- branch name is **project-management-app**
```suggestion
- repo name **project-management-app**. Branch name for develop - **develop**, **main** branch is empty and contains only README.md
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- the commit history should reflect the development process of the application. [Commit requirements](https://docs.rs.school/#/git-convention)
```suggestion
- the commit history should display application development process. [Commit requirements](https://docs.rs.school/#/git-convention)
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- add a link to the backend folder to the description of the pull request if the backend has not been deployed.
```suggestion
- describe in PR how to run your backend locally if you didn't deploy backend.
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- after completing the task, create a pull request **Merging a Pull Request is not required**
```suggestion
- after completing the task, create a pull request from **development** to **master** branch. **Merging a Pull Request is not required**
```

2022-09-02 17:32 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- localization (at least 2 languages). The application should be able to change the language by clicking on the slider in the header
```suggestion
- localization (at least 2 languages). You should be able to change the language by clicking on the toggler/select in header.
```

2022-09-07 15:31 UTC, MadaShindeInai requested changes

2022-09-07 15:31 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +### Header
```suggestion
### Header

- All Privite routes should contain sticky header. Moment when it become sticky (if there is a scroll on a page) should be animated: color can be changed or it's height can become smaller. [Animated sticky header](https://www.youtube.com/watch?v=hR8UW5CvYgw)
```

2022-09-07 15:31 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- Edit profile should redirect the user to a route with a form for edit profile. The requirements for the form are the same as for all forms in the application. There should be a 'Delete User' button
```suggestion
- Edit profile button should redirect the user to a route with a form for edit profile. The requirements for the form are the same as for all forms in the application. There should be a 'Delete User' button. In case of this action => "confirmation modal" => then the user should be logged out, and the user should be removed from the database.
```

2022-09-07 15:31 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- user login
```suggestion
- user auth
```

2022-09-07 15:31 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- Upon successful login, the user should be redirected to the "Main route"
```suggestion
- Upon successful login, the user should be redirected to the "Main route"
- If user already logged in and he try to reach this routes - he should be redirected to Main route.
```

2022-09-07 16:13 UTC, MadaShindeInai requested changes

2022-09-07 16:13 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- [ ] The user profile editing functionality is implemented. **30 points**
```suggestion
### Main route - max 8 points

- [ ] Board creation functionality **2 points**
- [ ] Displays all created boards as a list/grid **1 point**
- [ ] Each board in the list is displayed with a small preview of available information (title, description, etc). By clicking an element the user navigates to the board item (Board route). There's also a button for board deletion. **1 point**
- [ ] When trying to delete the board, we should receive a confirmation modal. The confirmation modal must be a generic component (one for the entire application). **1 points**
- [ ] The user profile editing functionality is implemented. **3 points**
```

2022-09-07 16:13 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- [ ] The column should have a delete button. By clicking -> confirmation modal -> when approving -> deleting. **10 points**
```suggestion
### Board route - max 26 points

- [ ] Button for column creation is displayed **1 point**
- [ ] If a board contains at least one column - a button for task creation is displayed/become enabled as well **1 points**
- [ ] A modal windows with forms is displayed for column and task creations  **3 points**
- [ ] A vertical scrollbar is displayed in the column when overflowing with the number of column tasks  **2 points**
- [ ] The page itself on the current route doesn't have a vertical scrollbar **1 points**
- [ ] With the help of drag-n-drop, we can swap columns. **3 points**
- [ ] With the help of drag-n-drop, we can change the order of tasks within a column.  **3 points**
- [ ] With the help of drag-n-drop, we can change the task belonging to the column.  **5 points**
- [ ] The functionality of viewing and editing of the task has been implemented. **3 points**
- [ ] The task must have a delete task button. On click: confirmation modal -> delete.  **1 points**
- [ ] At the top of the column should be Title. When you click on it, it should become an input, with Submit and Cancel buttons near it. After entering text in the input and clicking Submit - the Title of the column should change. **2 points**
- [ ] The column should have a delete button. By clicking -> confirmation modal -> when approving -> deleting. **1 points**
```

2022-09-07 16:13 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- [ ] Backend is deployed and publicly available **10 points**
```suggestion
### General requirements - max 11 points

- [ ] Backend error handling - (Not found, unhandled rejection, etc) should be performed in a user-friendly way (toast, pop-up or anything else you implement). **4 points**
- [ ] Localization **1 point**
- [ ] Backend is deployed and publicly available **2 points**
- [ ] Sticky header **2 points**
- [ ] Extra scope same complexity as Global search **2 points**
```

2022-09-07 16:13 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- [ ] Implemented additional functionality that is not provided for by current requirements **30 points**
```suggestion

```

2022-09-07 16:13 UTC, MadaShindeInai commented on tasks/react/project-management-system-EN.md
> +- [ ] Making commits after the deadline - **- 100 points**
```suggestion
### Penalties
- [ ] React default favicon **- 1 points**
- [ ] The presence of errors and warnings in the console  **- 2 points** for each
- [ ] The presence in the console of the results of the console.log execution - **- 2 points** for each
- [ ] @ts-ignore or any usage (search through github repo) - **- 1 point** for each
- [ ] Making commits after the deadline - **- 20 points**  

## Helpful links

- [Project management](https://ru.wikipedia.org/wiki/%D0%A3%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0%D0%BC%D0%B8)
- [What is a project?](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82_(%D0%B2_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B9_%D0%B4%D0%B5%D1%8F%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D1%81%D1%82%D0%B8))
- [Kanban](https://en.wikipedia.org/wiki/Kanban_(development))
```

2022-09-26 08:13 UTC, ragingyngvarr approved these changes

2022-09-26 08:16 UTC, merged